on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 pytest pytest-cov
      
      - name: Run unit tests with pytest
        run: pytest -v --cov --cov-report html

      - name: Format with black
        run: black Source

      - name: Lint with flake8
        run: flake8 --statistics

      - name: Code coverage report
        uses: codecov/codecov-action@v3.1.1

      #- name: Run deliverables (tasks)
      #  run: sh ./runtasks.sh

      #- name: Run applications
       # run: |
       #   python applications/....py
        #  python applications/....py
        # python applications/....py 5